# Generated by Django 3.2.9 on 2022-08-24 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код строки')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование МО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующая')),
                ('aro_available', models.BooleanField(default=False, verbose_name='АРО')),
                ('pso_n_available', models.BooleanField(default=False, verbose_name='ПСО (Н)')),
                ('pso_c_available', models.BooleanField(default=False, verbose_name='ПСО (К)')),
                ('ho_available', models.BooleanField(default=False, verbose_name='ХО')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('site', models.URLField(blank=True, max_length=100, null=True, verbose_name='Сайт')),
                ('level', models.SmallIntegerField(verbose_name='Уровень')),
                ('mo_type', models.CharField(choices=[('Центральные районные больницы', 'Центральные районные больницы'), ('Больницы', 'Больницы'), ('Поликлиники', 'Поликлиники'), ('Стоматологические поликлиники', 'Стоматологические поликлиники'), ('Станции скорой помощи', 'Станции скорой помощи'), ('Медицинские колледжи', 'Медицинские колледжи'), ('Санатории', 'Санатории'), ('Диспансеры', 'Диспансеры'), ('Родильные дома', 'Родильные дома'), ('Не определено', 'Не определено')], default='Не определено', max_length=30, verbose_name='Тип МО')),
            ],
            options={
                'verbose_name': 'Мед.организация',
                'verbose_name_plural': 'Мед.организации',
                'ordering': ['sn', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Должность')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('is_fired', models.BooleanField(default=False, verbose_name='Уволен')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
